### ISSUE TITLE
Remove your token

### ISSUE THREAD

**Issue by th0mk** [Snowfire01/ImageCharts.Net#1]
Hi, you should probably remove your token & secret:

https://github.com/Snowfire01/ImageCharts.Net/blob/3d1c9feb9065cbf574f288d07ff8ecc04fcf3cf9/FeatureTest/MainWindow.xaml.cs#L24

**Comment by leonschreiber96** [comment]
I should definitely do that, thank you very much for telling me!
It's just part of a quick commit I had to make to work on another machine and which I completely forgot about.
